scanner:
    diff_only: False

pycodestyle:
    max-line-length: 200
    ignore:
      - E203
      - W503

no_blank_comment: False
descending_issues_order: True
only_mention_files_with_errors: False
