# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

build:
  image: stable

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
#  fail_on_warning: true # < enable later...

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - epub
  - pdf

# use a conda environment
conda:
  environment: docs/environment.yml

python:
   version: 3.7
   install:
     - method: setuptools
       path: .