language: python
python:
 - 2.7
 - 3.3
 - 3.4
# install dependencies
before_install:
    - pip install numpy
    - pip install coverage
    - pip install coveralls
    - pip install pytest
    - pip install six
    - python ./test/gettestkernels.py
    - ls ./test
install:
    - python setup.py install
# run tests
script:
    - coverage run --source=SpiceyPy setup.py test
after_success:
    - coveralls