language: python
matrix:
    include:
        - os: linux
          python: 3.6
        - os: linux
          python: 3.7
        - os: linux
          python: 3.8
        - os: linux
          python: 3.9
        - os: linux
          python: 3.8
          env: CSPICE_SRC_DIR="/tmp/cspice"
        - os: linux
          python: 3.8
          env: CSPICE_SHARED_LIB="/tmp/cspice/lib/libcspice.so"
        - os: osx
          osx_image: xcode12
          language: generic
          env: PYVERSION='3.6.10'
        - os: osx
          osx_image: xcode12
          language: generic
          env: PYVERSION='3.7.9'
        - os: osx
          osx_image: xcode12
          language: generic
          env: PYVERSION='3.8.6'
        - os: osx
          osx_image: xcode12
          language: generic
          env: PYVERSION='3.9.0'

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then unset PYENV_ROOT && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash && export PATH="$HOME/.pyenv/bin:$PATH"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then eval "$(pyenv init -)"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv install --skip-existing $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv global $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv versions; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then python --version; fi
- pip install -U pip
- pip install -U wheel
- pip install twine
- pip install -r requirements.txt
- if ! [ -z "$CSPICE_SRC_DIR" ]; then wget -O - https://naif.jpl.nasa.gov/pub/naif/toolkit/C/PC_Linux_GCC_64bit/packages/cspice.tar.Z | gunzip -c | tar xC /tmp/ ; fi
- if ! [ -z "$CSPICE_SHARED_LIB"]; then mkdir -p /tmp/cspice/ && wget -O - https://anaconda.org/conda-forge/cspice/66/download/linux-64/cspice-66-h516909a_1009.tar.bz2 | tar xjC /tmp/cspice/ ; fi
install:
- python setup.py install
script:
- coverage run --source spiceypy -m pytest --pyargs spiceypy
after_success:
- codecov
deploy:
  provider: pypi
  user: andrewannex
  password:
    secure: YXA8LYIyAZ5HA2In4H/vUaCaVow9HbvKNT/TTT9OaH91Fszspr1uFo9mRQLNJlBViGgy2SaqNQITzlRdFyIcDstqRGPDQUw3xNIKvZ7YuHIzG1TVWNVpJsZf2ha1+JxozPTS2c2tlrS/LR7N4hYVtLOipaYAK2ucmB8sDu4dkws=
  on:
    tags: true
    branch: main
    repo: AndrewAnnex/SpiceyPy
