language: python
sudo: false
python:
- 2.7
- 3.5
before_install:
- pip install twine
- pip install -r requirements.txt
install:
- python setup.py install
script:
- coverage run --source=spiceypy setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: andrewannex
  password:
    secure: NhCK6eiiqI0pF6I1mJAh0sWCmPk3bqzE/37cfqs3AZlrf/a30UjibXvcVKtpfINnujIe0FRJbU9JsxCgfoNMhHfymC3V4Br0ponT1P4w5IY0POVsoZIVdQn8Hn0EAOFu/nkD1LOGOkOcb/2M8UB6PJ0/x2znbVjpDh4L27zCQNI=
  on:
    tags: true
    branch: master
    repo: AndrewAnnex/SpiceyPy
