language: python
python:
 - 2.7
 - 3.3
 - 3.4
# install dependencies
before_install:
    - pip install numpy
    - pip install coveralls
    - pip install pytest
    - python getspice.py
install:
    - python setup.py install
# run tests
script:
    - python setup.py test
after_success:
    - coveralls