language: python
python:
 - 2.7
 - 3.3
 - 3.4
# install dependencies
before_install:
    - pip install numpy
    - pip install coveralls
    - pip install pytest
install:
    - python setup.py install
# run tests
script:
    - py.test ./test/test_wrapper.py
after_success:
    - coveralls