language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          python: 3.7
          sudo: true
          dist: xenial
        - os: osx
          language: generic
          env: PYVERSION='2.7.13'
        - os: osx
          language: generic
          env: PYVERSION='3.5.4'
        - os: osx
          language: generic
          env: PYVERSION='3.6.0'
        - os: osx
          language: generic
          env: PYVERSION='3.7.0'

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated | grep -q pyenv && brew upgrade pyenv || true; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then eval "$(pyenv init -)"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv install $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv global $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv versions; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then python --version; fi
- pip install -U pip
- pip install -U wheel
- pip wheel numpy
- pip install numpy
- pip install twine
- pip install -r requirements.txt
install:
- python setup.py install
script:
- coverage run --source=spiceypy setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: andrewannex
  password:
    secure: YXA8LYIyAZ5HA2In4H/vUaCaVow9HbvKNT/TTT9OaH91Fszspr1uFo9mRQLNJlBViGgy2SaqNQITzlRdFyIcDstqRGPDQUw3xNIKvZ7YuHIzG1TVWNVpJsZf2ha1+JxozPTS2c2tlrS/LR7N4hYVtLOipaYAK2ucmB8sDu4dkws=
  on:
    tags: true
    branch: master
    repo: AndrewAnnex/SpiceyPy
