language: python
sudo: false
python:
 - 2.7
 - 3.3
 - 3.4
# install dependencies
before_install:
    - pip install --use-mirrors numpy
    - pip install --use-mirrors coverage
    - pip install --use-mirrors coveralls
    - pip install --use-mirrors six
install:
    - python setup.py install
# run tests
script:
    - coverage run --source=spiceypy setup.py test
after_success:
    - coveralls