language: python
sudo: false
python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5
# install dependencies
before_install:
    - pip install -r requirements.txt
install:
    - python setup.py install
script:
    - coverage run --source=spiceypy setup.py test
after_success:
    - coveralls