# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# This yml file was made in part by looking at the yml files for conda and astropy.

# This is not a .NET project, so we build SpiceyPy in the install step.
build: off

environment:
  global:
      WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\windows_sdk.cmd"

  matrix:
      - CONDA: "C:\\Miniconda"
        CONDA_BUILDS: C:\\Miniconda\conda-bld\win-32
        PYTHON_VERSION: "2.7.x"
        ARCH: "32"
        PLAT_NAME: "win32"
        PY_TAG: "cp27"

      - CONDA: "C:\\Miniconda-x64"
        CONDA_BUILDS: C:\\Miniconda-x64\conda-bld\win-64
        PYTHON_VERSION: "2.7.x"
        ARCH: "64"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp27"

      - CONDA: "C:\\Miniconda35"
        CONDA_BUILDS: C:\\Miniconda35\conda-bld\win-32
        PYTHON_VERSION: "3.5.x"
        ARCH: "32"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win32"
        PY_TAG: "cp35"

      - CONDA: "C:\\Miniconda35-x64"
        CONDA_BUILDS: C:\\Miniconda35-x64\conda-bld\win-64
        PYTHON_VERSION: "3.5.x"
        ARCH: "64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp35"

platform:
  - x64

cache:
  - C:\Users\appveyor\Downloads -> setup.py

install:
  # update path to have conda in it
  - set PATH=%CONDA%;%CONDA%/Scripts;%CONDA%/Library/bin;%PATH%
  # Log out the python version just so we know it
  - ECHO "%PYTHON_VERSION%"

  # Download things we absolutly need
  - pip install wheel twine six pytest
  - "conda install -q -y numpy"
  # coveralls and or coverage fail to install for 3.4 64bit python builds so don't bother for now.

  # Download CSPICE so we can build outside of python
  - "python getspice.py"

  # Now install spiceypy
  - IF "%ARCH%"=="32" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86) ELSE (ECHO "probably a 64bit build")
  - IF "%ARCH%"=="64" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64) ELSE (ECHO "probably a 32bit build")
  - "python setup.py install"
  - ECHO "Installed SpiceyPy!"


test_script:
  - "py.test spiceypy/tests"

after_test:
  - ECHO "DONE!"
  - dir
  - ECHO "BUILDING WHEELS..."
  - "python setup.py sdist bdist_wheel --plat-name=%PLAT_NAME% --python-tag=%PY_TAG%"
  - ECHO "BUILDING CONDA PACKAGE..."
  # Update to a known good conda, found from https://github.com/numba/numba/blob/master/appveyor.yml
  # (to workaround http://help.appveyor.com/discussions/problems/4910)
  - "conda install -q -y conda=4.1.4"
  - "conda install -q -y conda-build"
  - "conda build appveyor -q --no-anaconda-upload"
  - ps: ls $env:CONDA_BUILDS
  - ps: cp $env:CONDA_BUILDS\*.* .\dist\
  - ps: ls .\dist\


artifacts:
  - path: dist\*

