# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# This yml file was made in part by looking at the yml files for conda and astropy.

# This is not a .NET project, so we build SpiceyPy in the install step.
build: off

environment:
  global:
      WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\windows_sdk.cmd"
  BINSTAR_TOKEN:
    secure: 4g8YIaW6BcGaDKmgMsOWhySjKp18AHMtCNtzs7i8FN8FRfWswW3XFUVCec33pJwK
  PYPI_PASSWORD:
    secure: ojP0ftEgmrZcijN49vQEPz39rkcPyOxtjwNp5hUYkdKxQq47DwkiaWOnVA11nog637VUmRnHb07uXwvrhK4bbg==

  matrix:
      - PYTHON: "C:\\Python27-x64"
        CONDA: "C:\\Miniconda-x64"
        CONDA_BUILDS: C:\\Miniconda-x64\conda-bld\win-64
        PYTHON_VERSION: "2.7.x"
        ARCH: "64"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp27"

      - PYTHON: "C:\\Python34-x64"
        CONDA: "C:\\Miniconda3-x64"
        CONDA_BUILDS: C:\\Miniconda3-x64\conda-bld\win-64
        PYTHON_VERSION: "3.4.x"
        ARCH: "64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp34"

      - PYTHON: "C:\\Python35-x64"
        CONDA: "C:\\Miniconda35-x64"
        CONDA_BUILDS: C:\\Miniconda35-x64\conda-bld\win-64
        PYTHON_VERSION: "3.5.x"
        ARCH: "64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp35"

      - PYTHON: "C:\\Python36-x64"
        CONDA: "C:\\Miniconda36-x64"
        CONDA_BUILDS: C:\\Miniconda36-x64\conda-bld\win-64
        PYTHON_VERSION: "3.6.x"
        ARCH: "64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp36"

platform:
  - x64

cache:
  - C:\Users\appveyor\Downloads -> setup.py

install:
  # Log out the python version just so we know it
  - ECHO "%PYTHON_VERSION%"

  # update path to use installed pip
  - set PATH=%PYTHON%\\scripts;%PATH%

  # Download things we absolutly need
  - pip install wheel twine six pytest
  # coveralls and or coverage fail to install for 3.4 64bit python builds so don't bother for now.

  # Check for numpy wheel, compile if absent
  - "powershell appveyor\\install_numpy.ps1"

  # Now install numpy from pre-built wheel. This may be fragile.
  - "%WITH_COMPILER% pip install --use-wheel --no-index --find-links=c:\\Users\\appveyor\\Downloads numpy"

  # Download CSPICE so we can build outside of python
  - "%PYTHON%/python getspice.py"

  # Make a backup of the PATH just in case.
  - set BK_PATH=%PATH%

  # Now install spiceypy
  - IF "%ARCH%"=="32" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86) ELSE (ECHO "probably a 64bit build")
  - IF "%ARCH%"=="64" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64) ELSE (ECHO "probably a 32bit build")
  - "%PYTHON%/python setup.py install"

  - ECHO "Installed SpiceyPy!"
  # restore PATH
  - set PATH=%BK_PATH%
  - "%PYTHON%/Scripts/py.test --version"

test_script:
  - "%PYTHON%/Scripts/py.test spiceypy/tests"

after_test:
  - ECHO "DONE!"
  - ECHO "BUILDING WHEELS..."
  - "%PYTHON%/python setup.py sdist bdist_wheel --plat-name=%PLAT_NAME% --python-tag=%PY_TAG%"
  - ECHO "BUILDING CONDA PACKAGE..."
  - set BK_PATH=%PATH%

  # try conda thing
  - set PATH=%CONDA%;%CONDA%/Scripts;%CONDA%/Library/bin;%PATH%
  # Update to a known good conda, found from https://github.com/numba/numba/blob/master/appveyor.yml
  - "conda install -q -y conda=4.3.14"
  - "conda install -q -y conda-build anaconda-client numpy wheel six pytest"
  - "conda build appveyor -q --no-anaconda-upload"
  - ps: ls $env:CONDA_BUILDS
  - ps: mv $env:CONDA_BUILDS ./
  - ps: rm dist/*.egg
  - set PATH=%BK_PATH%


artifacts:
  - path: dist\*
    name: pypiartifacts

  - path: 'win-*\*.tar.bz2'
    name: condaartifacts

deploy_script:
  - echo "Starting Artifact Deployment"
  # populate pypirc file for twine
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo repository=https://pypi.python.org/pypi     >> %USERPROFILE%\\.pypirc
  - echo username=andrewannex                        >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  # upload to pypi for windows
  - set PATH=%BK_PATH%
  - set HOME=%USERPROFILE%
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { Invoke-Expression "twine upload -r pypi --skip-existing dist/*" 2>$null } Else { write-output "Not on a tag on master, won't deploy to pypi"}
  # upload conda builds to conda cloud
  - cmd: set PATH=%CONDA%;%CONDA%/Scripts;%CONDA%/Library/bin;%PATH%
  # because appveyor prints to stderror, we will run it in command mode by doing a check firs
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { $env:conda_upload = 'true' } Else { write-output "Not on a tag on master, won't deploy to anaconda" }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %BINSTAR_TOKEN% upload .\win-*\*.tar.bz2 -u andrewannex --no-progress --force
  - echo "Finished Artifact Deployment"
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3a0242522a806d39ba2b
    method: POST