__author__ = 'Apollo117'

import SpiceyPy as spice

c = spice.stypes.SPICEDOUBLE_CELL(10)
print(c)
print(c.data)
print([x for x in c])
spice.appndd(1.0, c)
spice.appndd(3.0, c)
spice.appndd(3.0, c)
d = spice.copy(c)
print("copied c as d")
print(d)
print([x for x in d])
spice.appndd(3.0, c)
spice.appndd(3.0, c)
spice.appndd(3.0, c)
spice.appndd(3.0, c)
print("copied c as d")
print([x for x in d])
print(c)
print(c.data)
print([x for x in c])
print(spice.card(c))
print(spice.size(c))
c = spice.scard(6, c)
print(c)
print(c.data)
print([x for x in c])
print(spice.card(c))
print(spice.size(c))
c = spice.scard(0, c)
print(c)
print(c.data)
print([x for x in c])
print(spice.card(c))
print(spice.size(c))
c = spice.ssize(16, c)
print(c)
print(c.data)
print([x for x in c])
print(spice.card(c))
print(spice.size(c))
print("copied c as d")
print([x for x in d])
print(d)
print(c)

setone = spice.stypes.SPICEINT_CELL(10)
spice.appndi(1, setone)
spice.appndi(2, setone)
spice.appndi(3, setone)
settwo = spice.stypes.SPICEINT_CELL(10)
spice.appndi(2, settwo)
spice.appndi(3, settwo)
spice.appndi(4, settwo)
difference = spice.diff(setone, settwo)
print("Difference: ", difference)
print([x for x in difference])