name: SPICEYPY_DOCS

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9
  - numpy
  - sphinx==2.3.1
  - myst-parser
  - sphinx-copybutton
  - pip
  - pip:
    - sphinx_autodoc_typehints

