name: SPICEYPY_DOCS

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.11
  - numpy
  - sphinx>=3.1.2
  - myst-parser
  - sphinx-copybutton
  - pip
  - pip:
    - sphinx_autodoc_typehints

