name: SPICEYPY_DOCS

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10
  - numpy==1.25.2
  - myst-parser==2.0.0
  - docutils
  - graphviz
  - sphinx<=7.0.0
  - sphinx-copybutton
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - recommonmark
  - pip
variables:
  CONDA_APPEND_CORE_REQUIREMENTS: False
